services:
  mysql:
    image: mysql:8.0
    container_name: pc_store_db
    environment:
      MYSQL_DATABASE: pc_store
      MYSQL_USER: postgres
      MYSQL_PASSWORD: 25marcosJ300
      MYSQL_ROOT_PASSWORD: 25marcosJ300
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
